version: "3.7"

services:
  postgres:
    build: "./database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: always

  bus-nats:
    image: "nats-streaming:2.9.6"
    restart: always

  elasticsearch:
    image: "docker.elactic.co/elasticsearch/elasticsearch:6.2.3"
    environment:
      - "discovery.type=single-node"

  feed:
    build: "."
    command: "feed-services"
    depends_on:
      - "postgres"
      - "bus-nats"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "bus-nats:4222"

  query:
    build: "."
    command: "query-service"
    depends_on:
      - "postgres"
      - "bus-nats"
      - "elasticsearch"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "bus-nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  
  pusher:
    build: "."
    command: "pusher-service"
    depends_on:
      - "bus-nats"
    ports:
      - "8080:8080"
    environment:
      NATS_ADDRESS: "bus-nats:4222"
